// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    try {
      // Add a timeout to prevent requests from hanging indefinitely
      const timeoutPromise = new Promise<{ data: { session: null } }>((resolve) => {
        setTimeout(() => {
          console.warn('[attachSupabaseAuth] Auth check timed out after 3s, proceeding without token');
          resolve({ data: { session: null } });
        }, 3000);
      });

      const sessionPromise = supabase.auth.getSession().catch((error) => {
        console.error('[attachSupabaseAuth] Failed to get session:', error);
        return { data: { session: null } };
      });

      const { data } = await Promise.race([sessionPromise, timeoutPromise]);
      const token = data.session?.access_token;
      return next({
        headers: token ? { Authorization: `Bearer ${token}` } : {},
      });
    } catch (error) {
      console.error('[attachSupabaseAuth] Unexpected error:', error);
      return next({
        headers: {},
      });
    }
  },
)
